# Foreword by Alexis Fink {.unnumbered .unlisted}

The explosion of data availability and analytical tooling in the past few years has changed the
landscape for analytical work. Advanced, easy to use reporting tools are now nearly ubiquitous.
Many organizations have adopted tools that can ferret out relationships among organizational
features and present them cleanly in only a few clicks. This increase in availability of compute
power, emergence of friendly analytic tools and an explosion of data have created a wonderful
opportunity to bring more thoughtful analytical rigor to nearly every imaginable question. Not
coincidentally, organizations are increasingly looking to apply all that data and capability to
what is typically their greatest area of expense and their greatest strategic differentiator---their
people.

For too long, many of the most critical decisions in an organization—--people decisions—--had
been guided by gut instinct or borrowed ‘best practices.’  The field of People Analytics
expanded beyond its Industrial-Organizational Psychology roots to incorporate a wider range of
questions and methods. As wide data availability created an expectation of quantitative
answers to people questions, HR professionals who had dedicated their careers to solving
people problems needed more sophisticated analysis and data storytelling to make their cases
and to refine their approaches for greater efficiency, effectiveness and impact. Data Scientists
and Analysts from other fields began to move into People Analytics teams.

Doing data work with people in organizations has complexities that some other types of data
work doesn’t. Often, the employee populations are relatively smaller than data sets used in
other areas, sometimes limiting the methods that can be used. Various regulatory requirements
may dictate what data can be gathered and used, and what types of evidence might be
required for various programs or people strategies. Human behavior and organizations are
sufficiently complex that typically, multiple factors work together in influencing an outcome.
Effects can be subtle or meaningful only in combination, or difficult to tease apart. The
availability of expert knowledge on past behavior makes Bayesian methods particularly relevant, though not (yet)
widely used. While in many disciplines, prediction is the most important aim, for most people
analytics projects and practitioners, understanding *why* something is happening is critical.
Causal inference is the lifeblood of organizational change---simply describing what is happening
without helping the organization bend the curve to make a better thing happen is People
Analytics malpractice!

Frequently, analytics in organizations address two variables at a time---one independent and
one dependent variable. However, organizational questions are almost never that simple.  Reducing workers to just a level, location, tenure, or job profile masks the complexity and nuance required to make meaningful improvements. We need to do better. The universe of analytical approaches is wonderful and vast, but the best ‘Swiss army knife’ we have in People Analytics is regression.

Regression is a family of techniques, and choosing the right approach is essential to delivering
meaningful, useful insight. This volume is an accessible, targeted work aimed directly at
supporting professionals doing People Analytics work, with examples that are relevant to that
domain and sensitive to the unique constraints People Analytics professionals face. This
updated second edition expands the toolset, illustrating how Bayesian inference can be
incorporated into regression techniques, and helping readers structure their analyses carefully
to enable causal inference on the basis of regression analyses.

I’ve had the privilege of knowing and respecting Keith McNulty for many years---he is the rare
and marvelous individual who is deeply expert in the mechanics of data and analytics, curious
about and steeped in the opportunities to improve the effectiveness and well-being of people
at work, and a gifted teacher and storyteller. He is among the most prolific standard-bearers for
People Analytics. This new open-source volume is in keeping with many years of contributions
to the practice of understanding people at work.

After over 30 years of doing People Analytics work and the privilege of leading People Analytics
teams at several leading global organizations, I am still excited by the problems we get to solve,
the insights we get to spawn, and the tremendous impact we can have on organizations and the
people that comprise them. This work is human and technical and important and exciting and
deeply gratifying. I hope that you will find this second edition of the *Handbook of Regression
Modeling in People Analytics* helps you uncover new truths and create positive impacts in your
own work.

::: {.content-visible unless-format="pdf"}
[Alexis A. Fink](https://www.linkedin.com/in/alexisfink/) \
March 2026
:::

::: {.content-visible when-format="pdf"}
Alexis A. Fink \
March 2026
:::



***Alexis A. Fink, PhD** is a leading figure in people analytics and has led major people analytics
teams at Meta, Microsoft and Intel. She is a Fellow and Past President of the Society for
Industrial and Organizational Psychology and is a frequent advisor, author, journal editor and
research leader in her field.*
