name: Feature Request
description: Suggest new content, examples, or improvements
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement! We appreciate ideas that make this book more valuable to the community.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you suggesting?
      options:
        - New content topic or chapter
        - Additional code example (R)
        - Additional code example (Python)
        - Expanded explanation or clarification
        - New dataset or case study
        - Structural improvement
        - Tool or resource addition
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Provide a clear description of what you'd like to see added or changed
      placeholder: "It would be helpful to have a section on..."
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why would this feature benefit the book and its readers?
      placeholder: "This would help readers understand... / Many practitioners struggle with..."
    validations:
      required: true

  - type: dropdown
    id: target-audience
    attributes:
      label: Target Audience
      description: Who would benefit most from this feature?
      multiple: true
      options:
        - Beginners in regression modeling
        - Intermediate practitioners
        - Advanced users
        - People analytics professionals
        - Data scientists
        - Researchers/academics
        - R users specifically
        - Python users specifically
        - All readers
    validations:
      required: false

  - type: textarea
    id: suggested-implementation
    attributes:
      label: Suggested Implementation
      description: "If you have ideas about how this could be implemented, please share them"
      placeholder: "This could be added to Chapter X, or as a new section covering..."
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Are there examples, papers, or other resources that illustrate this feature?
      placeholder: "Similar to the approach in [book/paper]... or See this tutorial: [link]"
    validations:
      required: false

  - type: dropdown
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be interested in contributing this feature yourself?
      options:
        - "Yes, I'd like to contribute this"
        - "Maybe, depending on complexity"
        - "No, just suggesting"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this hasn't been suggested before
          required: true
        - label: I have reviewed the CONTRIBUTING.md guidelines
          required: false
