<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Keith McNulty">

<title>8&nbsp; Poisson, Quasi-Poisson and Negative Binomial Regression for Count Outcomes – Handbook of Regression Modeling in People Analytics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./hierarchical_data.html" rel="next">
<link href="./ordinal_regression.html" rel="prev">
<link href="./www/cover/coverpage-og.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-108e51fa0b95596792f9f0eaa63a27ea.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-N7JZGMVRZK"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-N7JZGMVRZK', { 'anonymize_ip': true});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="8&nbsp; Poisson, Quasi-Poisson and Negative Binomial Regression for Count Outcomes – Handbook of Regression Modeling in People Analytics">
<meta property="og:description" content="">
<meta property="og:image" content="https://peopleanalytics-regression-book.org/poisson_nb_files/figure-html/unnamed-chunk-1-1.png">
<meta property="og:site_name" content="Handbook of Regression Modeling in People Analytics">
<meta property="og:image:height" content="960">
<meta property="og:image:width" content="1344">
<meta name="twitter:title" content="8&nbsp; Poisson, Quasi-Poisson and Negative Binomial Regression for Count Outcomes – Handbook of Regression Modeling in People Analytics">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://peopleanalytics-regression-book.org/poisson_nb_files/figure-html/unnamed-chunk-1-1.png">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./poisson_nb.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Poisson, Quasi-Poisson and Negative Binomial Regression for Count Outcomes</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Handbook of Regression Modeling in People Analytics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/keithmcnulty/regression-handbook-2nd-edition" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foreword.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foreword by Alexis Fink</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./importance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">The Importance of Regression in People Analytics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Basics of the R Programming Language</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./primer_stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Statistics Foundations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Linear Regression for Continuous Outcomes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binomial_logistic_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Binomial Logistic Regression for Binary Outcomes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multinomial_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multinomial Logistic Regression for Nominal Category Outcomes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ordinal_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Proportional Odds Logistic Regression for Ordered Category Outcomes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson_nb.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Poisson, Quasi-Poisson and Negative Binomial Regression for Count Outcomes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hierarchical_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modeling Explicit and Latent Hierarchy in Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Survival Analysis for Modeling Singular Events Over Time</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./power_tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Power Analysis for Estimating Required Sample Sizes for Modeling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayesian_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bayesian Inference - A Modern Alternative to Classical Statistical Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayesian_linear_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Linear Regression Using Bayesian Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./other_bayesian_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Fitting Other Regression Models Using Bayesian Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Causal Inference - Moving From Association to Causation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./further.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Further Exercises for Practice</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bibliography.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#when-to-use-it" id="toc-when-to-use-it" class="nav-link active" data-scroll-target="#when-to-use-it"><span class="header-section-number">8.1</span> When to use it</a>
  <ul class="collapse">
  <li><a href="#sec-poisson-origins" id="toc-sec-poisson-origins" class="nav-link" data-scroll-target="#sec-poisson-origins"><span class="header-section-number">8.1.1</span> Origins and intuition of the Poisson distribution</a></li>
  <li><a href="#use-cases-for-count-regression" id="toc-use-cases-for-count-regression" class="nav-link" data-scroll-target="#use-cases-for-count-regression"><span class="header-section-number">8.1.2</span> Use cases for count regression</a></li>
  <li><a href="#sec-walkthrough-poisson" id="toc-sec-walkthrough-poisson" class="nav-link" data-scroll-target="#sec-walkthrough-poisson"><span class="header-section-number">8.1.3</span> Walkthrough example</a></li>
  </ul></li>
  <li><a href="#sec-mod-poisson" id="toc-sec-mod-poisson" class="nav-link" data-scroll-target="#sec-mod-poisson"><span class="header-section-number">8.2</span> Modeling count outcomes with Poisson regression</a>
  <ul class="collapse">
  <li><a href="#the-poisson-model-and-the-log-transformation" id="toc-the-poisson-model-and-the-log-transformation" class="nav-link" data-scroll-target="#the-poisson-model-and-the-log-transformation"><span class="header-section-number">8.2.1</span> The Poisson model and the log transformation</a></li>
  <li><a href="#fitting-and-interpreting-a-poisson-regression-model" id="toc-fitting-and-interpreting-a-poisson-regression-model" class="nav-link" data-scroll-target="#fitting-and-interpreting-a-poisson-regression-model"><span class="header-section-number">8.2.2</span> Fitting and interpreting a Poisson regression model</a></li>
  </ul></li>
  <li><a href="#sec-overdispersion" id="toc-sec-overdispersion" class="nav-link" data-scroll-target="#sec-overdispersion"><span class="header-section-number">8.3</span> Model diagnostics: overdispersion</a>
  <ul class="collapse">
  <li><a href="#detecting-overdispersion" id="toc-detecting-overdispersion" class="nav-link" data-scroll-target="#detecting-overdispersion"><span class="header-section-number">8.3.1</span> Detecting overdispersion</a></li>
  <li><a href="#quasi-poisson-regression" id="toc-quasi-poisson-regression" class="nav-link" data-scroll-target="#quasi-poisson-regression"><span class="header-section-number">8.3.2</span> Quasi-Poisson regression</a></li>
  <li><a href="#negative-binomial-regression" id="toc-negative-binomial-regression" class="nav-link" data-scroll-target="#negative-binomial-regression"><span class="header-section-number">8.3.3</span> Negative binomial regression</a></li>
  <li><a href="#comparing-poisson-and-negative-binomial-models" id="toc-comparing-poisson-and-negative-binomial-models" class="nav-link" data-scroll-target="#comparing-poisson-and-negative-binomial-models"><span class="header-section-number">8.3.4</span> Comparing Poisson and negative binomial models</a></li>
  </ul></li>
  <li><a href="#other-considerations-in-count-regression" id="toc-other-considerations-in-count-regression" class="nav-link" data-scroll-target="#other-considerations-in-count-regression"><span class="header-section-number">8.4</span> Other considerations in count regression</a>
  <ul class="collapse">
  <li><a href="#prediction" id="toc-prediction" class="nav-link" data-scroll-target="#prediction"><span class="header-section-number">8.4.1</span> Prediction</a></li>
  <li><a href="#exposure-and-offsets" id="toc-exposure-and-offsets" class="nav-link" data-scroll-target="#exposure-and-offsets"><span class="header-section-number">8.4.2</span> Exposure and offsets</a></li>
  <li><a href="#zero-inflation" id="toc-zero-inflation" class="nav-link" data-scroll-target="#zero-inflation"><span class="header-section-number">8.4.3</span> Zero-inflation</a></li>
  </ul></li>
  <li><a href="#poisson-and-negative-binomial-regression-using-python" id="toc-poisson-and-negative-binomial-regression-using-python" class="nav-link" data-scroll-target="#poisson-and-negative-binomial-regression-using-python"><span class="header-section-number">8.5</span> Poisson and negative binomial regression using Python</a></li>
  <li><a href="#learning-exercises" id="toc-learning-exercises" class="nav-link" data-scroll-target="#learning-exercises"><span class="header-section-number">8.6</span> Learning exercises</a>
  <ul class="collapse">
  <li><a href="#discussion-questions" id="toc-discussion-questions" class="nav-link" data-scroll-target="#discussion-questions"><span class="header-section-number">8.6.1</span> Discussion questions</a></li>
  <li><a href="#data-exercises" id="toc-data-exercises" class="nav-link" data-scroll-target="#data-exercises"><span class="header-section-number">8.6.2</span> Data exercises</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/keithmcnulty/regression-handbook-2nd-edition/edit/main/poisson_nb.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/keithmcnulty/regression-handbook-2nd-edition/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-count-reg" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Poisson, Quasi-Poisson and Negative Binomial Regression for Count Outcomes</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p></p>
<p>In the previous chapters, we have explored how to model outcomes that are continuous, binary or multinomial in nature. We now turn our attention to another common type of data in people analytics: count data. Count data consists of non-negative integers (0, 1, 2, 3, …) that represent the number of times an event has occurred within a specific period of time, location, or group. Examples in the workplace are numerous: the number of safety incidents in a factory per month, the number of days an employee was absent in a year, or the number of customer complaints received by a service agent in a week.</p>
<p>Because count data is not continuous and is bounded below at zero, linear regression is not appropriate. The assumptions of normality and constant variance of residuals are typically violated. A linear model could also illogically predict negative counts. While we could model a binary outcome (e.g., ‘had at least one absence’ vs.&nbsp;‘had zero absences’) using logistic regression, this approach throws away a lot of valuable information about the magnitude of the count.</p>
<p>To properly model count outcomes, we turn to other members of the generalized linear model (GLM) family. First we will look at Poisson regression. Poisson regression is specifically designed for count data and, like logistic regression, uses a transformation–—in this case, the natural logarithm—–to establish a linear relationship between the input variables and the (transformed) outcome. However, Poisson regression rests on a very strong assumption that the mean and variance of the count variable are equal. When this assumption is violated, a condition known as <em>overdispersion</em> (or more rarely <em>underdispersion</em>) occurs, and the Poisson model’s estimates can become unreliable. In this case, we will see that related models, namely Quasi-Poisson or negative binomial regression models, provide more flexible alternatives. Mastering these techniques is essential for any analyst who wants to understand the drivers of event-based phenomena in the workplace.</p>
<section id="when-to-use-it" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="when-to-use-it"><span class="header-section-number">8.1</span> When to use it</h2>
<section id="sec-poisson-origins" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="sec-poisson-origins"><span class="header-section-number">8.1.1</span> Origins and intuition of the Poisson distribution</h3>
<p>The Poisson distribution is named after the French mathematician Siméon Denis Poisson, who introduced it in 1837 in a work that focused on the probability of wrongful convictions in court cases<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. However, the distribution’s most famous early application came sixty years later from the Polish-Russian economist and statistician Ladislaus von Bortkiewicz.</p>
<p>Bortkiewicz analyzed data on the number of Prussian cavalry soldiers who were fatally kicked by their horses each year across 14 different army corps over a 20-year period. He observed that this was a “rare event.” In any given corps in any given year, the number of deaths was very low, but often not zero. He found that the observed frequency of 0, 1, 2, or more deaths per corps-year closely matched the predictions of the Poisson distribution. The key insight is that the Poisson distribution effectively models the number of times an event occurs in a fixed interval of time or space, given that these events happen with a known constant mean rate (denoted by <span class="math inline">\(\lambda\)</span>) and are independent of the time since the last event. The shape of the distribution for different mean rates is shown in <a href="#fig-poisson-dist" class="quarto-xref">Figure&nbsp;<span>8.1</span></a>. For a low mean, the distribution is highly skewed with most observations at or near zero. As the mean increases, the distribution becomes more symmetric and starts to resemble a normal distribution.</p>
<p>The core idea of modeling rates is central to Poisson regression. We are not just modeling a count; we are modeling the <em>expected rate</em> at which events occur, and then examining how different factors or characteristics influence that rate.</p>
<div id="fig-poisson-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-poisson-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poisson_nb_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-poisson-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1: Poisson distributions showing how the shape changes with different mean event rates <span class="math inline">\(\lambda\)</span>
</figcaption>
</figure>
</div>
</section>
<section id="use-cases-for-count-regression" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="use-cases-for-count-regression"><span class="header-section-number">8.1.2</span> Use cases for count regression</h3>
<p>Poisson, Quasi-Poisson and negative binomial regression can be used when the outcome of interest is a count of events. Here are some example questions that could be approached using these methods:</p>
<ul>
<li>What are the characteristics of employees that are associated with a higher number of days of unplanned absence per year?</li>
<li>What are the characteristics of job openings that are associated with a higher number of referrals from existing employees?</li>
<li>What elements in a factory’s environment are related to the number of safety incidents per month?</li>
</ul>
</section>
<section id="sec-walkthrough-poisson" class="level3" data-number="8.1.3">
<h3 data-number="8.1.3" class="anchored" data-anchor-id="sec-walkthrough-poisson"><span class="header-section-number">8.1.3</span> Walkthrough example</h3>
<p>You are an analyst at a large technology firm. The HR leadership team is concerned about employee absenteeism and wants to understand what factors are associated with higher absenteeism in order to better target support and intervention programs. They believe that factors like an employee’s tenure with the company, their performance, and whether or not they are a manager could all play a role.</p>
<p>You are provided with a data set of 865 employees for the most recent full year. The <code>absenteeism</code> data set contains the following fields:</p>
<ul>
<li><code>days_absent</code>: The number of unscheduled days of absence for the employee in the last calendar year (our outcome variable).</li>
<li><code>tenure</code>: The employee’s tenure at the company in years.</li>
<li><code>is_manager</code>: A binary value indicating 1 if the employee is a manager and 0 if not.</li>
<li><code>performance_rating</code>: The employee’s most recent performance score on an increasing scale from 1 to 5.</li>
</ul>
<p>Let’s download the <code>absenteeism</code> data set and take a quick look at it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># if needed, download data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://peopleanalytics-regression-book.org/data/absenteeism.csv"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>absenteeism <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(url)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(absenteeism)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  days_absent tenure is_manager performance_rating
1           2     16          0                  2
2          13      4          0                  5
3           0      0          0                  3
4           8     24          0                  5
5          12      9          0                  3
6           8      3          0                  4</code></pre>
</div>
</div>
<p>The data looks as expected, but we should do some type conversion for the <code>is_manager</code> column before we get a summary.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert is_manager to factor</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>absenteeism<span class="sc">$</span>is_manager <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(absenteeism<span class="sc">$</span>is_manager)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(absenteeism)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div style="page-break-after: always;"></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  days_absent        tenure      is_manager performance_rating
 Min.   : 0.00   Min.   : 0.00   0:753      Min.   :1.000     
 1st Qu.: 3.00   1st Qu.: 8.00   1:112      1st Qu.:3.000     
 Median : 7.00   Median :15.00              Median :3.000     
 Mean   :10.26   Mean   :15.16              Mean   :3.473     
 3rd Qu.:14.00   3rd Qu.:23.00              3rd Qu.:4.000     
 Max.   :62.00   Max.   :30.00              Max.   :5.000     </code></pre>
</div>
</div>
<p>We see that <code>days_absent</code> ranges from 0 to 62, with a mean of 10.26. The distribution of absences is shown in <a href="#fig-daysabsent-dist" class="quarto-xref">Figure&nbsp;<span>8.2</span></a>.</p>
<div id="fig-daysabsent-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-daysabsent-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poisson_nb_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-daysabsent-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2: Distribution of <code>days_absent</code> with histogram and density plot
</figcaption>
</figure>
</div>
<p>This is a highly right-skewed distribution, with most employees having a low number of absences and a “long tail” of employees with a high number of absences. This is a classic shape for count data, and suggests that Poisson regression is a good initial approach for this problem.</p>
</section>
</section>
<section id="sec-mod-poisson" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="sec-mod-poisson"><span class="header-section-number">8.2</span> Modeling count outcomes with Poisson regression</h2>
<p>We cannot directly model a count outcome with a linear equation because the expected count must be non-negative. As with logistic regression, we will need a transformation to connect the linear combination of our input variables to the expected count.</p>
<section id="the-poisson-model-and-the-log-transformation" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="the-poisson-model-and-the-log-transformation"><span class="header-section-number">8.2.1</span> The Poisson model and the log transformation</h3>
<p>The formula for the Poisson distribution gives the probability of observing exactly <span class="math inline">\(k\)</span> events in an interval, given a mean event rate of <span class="math inline">\(\lambda\)</span>:</p>
<p><span class="math display">\[
P(Y=k) = \frac{\lambda^k e^{-\lambda}}{k!}
\]</span></p>
<p>We assume that the expected event count <span class="math inline">\(\lambda_i\)</span> for each individual observation <span class="math inline">\(i\)</span> depends on that observation’s input variables <span class="math inline">\(x_{1i}, x_{2i}, \dots, x_{pi}\)</span>. To ensure that our outcome is always positive, we model the <em>natural logarithm</em> of <span class="math inline">\(\lambda_i\)</span> as a linear function of the input variables. This is the <em>log transformation</em>.</p>
<p><span class="math display">\[
\ln(\lambda_i) = \beta_0 + \beta_1x_{i1} + \beta_2x_{i2} + \cdots + \beta_px_{ip}
\]</span></p>
<p>This equation should look familiar. It’s a linear model, just like in linear regression. The crucial difference is that we are not modeling the expected count outcome directly; we are modeling the <em>log of the expected count</em>.</p>
<p>By exponentiating both sides, we can see how the input variables relate to the expected count itself:</p>
<p><span class="math display">\[
\begin{aligned}
\lambda_i &amp;= e^{\beta_0 + \beta_1x_{i1} + \beta_2x_{i2} + \cdots + \beta_px_{ip}} \\
&amp;= e^{\beta_0}(e^{\beta_1})^{x_{i1}}(e^{\beta_2})^{x_{i2}}\cdots(e^{\beta_p})^{x_{ip}}
\end{aligned}
\]</span></p>
<p>This shows that the effects of the input variables are multiplicative on the expected count <span class="math inline">\(\lambda_i\)</span>. This is analogous to work we have done in previous chapters, where exponentiated logistic regression coefficients have a multiplicative effect on the odds of an outcome.</p>
</section>
<section id="fitting-and-interpreting-a-poisson-regression-model" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="fitting-and-interpreting-a-poisson-regression-model"><span class="header-section-number">8.2.2</span> Fitting and interpreting a Poisson regression model</h3>
<p>Let’s fit a Poisson model to our <code>absenteeism</code> data to understand which inout variables are associated with absent days. We use the <code>glm()</code> function, specifying <code>family = "poisson"</code> which automatically uses the log transformation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run a poisson model</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>absent_poisson_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> days_absent <span class="sc">~</span> tenure <span class="sc">+</span> is_manager <span class="sc">+</span> performance_rating,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> absenteeism,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"poisson"</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># view the summary</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(absent_poisson_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = days_absent ~ tenure + is_manager + performance_rating, 
    family = "poisson", data = absenteeism)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         1.505418   0.054170  27.791  &lt; 2e-16 ***
tenure              0.051144   0.001270  40.280  &lt; 2e-16 ***
is_manager1        -0.157984   0.033025  -4.784 1.72e-06 ***
performance_rating -0.009937   0.013878  -0.716    0.474    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 7544.2  on 864  degrees of freedom
Residual deviance: 5799.6  on 861  degrees of freedom
AIC: 8927

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>The summary output is similar to what we’ve seen before. We have coefficient estimates, standard errors, z-values, and p-values. Let’s interpret the <code>tenure</code> coefficient. For a one-year increase in <code>tenure</code>, the log of the expected number of absent days increases by 0.0511, holding all other variables constant. A much more intuitive interpretation comes from exponentiating the coefficients. The exponentiated value is called an <strong>Incidence Rate Ratio (IRR)</strong>. The IRR tells us the multiplicative factor by which the expected count changes for a one-unit increase in the input variable.</p>
<p>Let’s calculate the IRRs for our model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exponentiate coefficients to get Incidence Rate Ratios (IRRs)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>(irr <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(absent_poisson_model)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       (Intercept)             tenure        is_manager1 performance_rating 
         4.5060347          1.0524742          0.8538633          0.9901123 </code></pre>
</div>
</div>
<p>Now we can interpret these more easily:</p>
<ul>
<li><code>**Intercept:**</code> 4.51 is the expected number of absent days for a brand new non-manager with a performance rating of 1. This is not practically meaningful, but serves as the baseline for the model.</li>
<li><code>**tenure:**</code> The IRR is 1.0525. For each additional year of tenure, the expected count of absent days increases by about 5%, holding other factors constant.</li>
<li><code>**is_manager1:**</code> The IRR is 0.8539. This means that being a manager (compared to not being a manager) is associated with an expected absent day count that is 0.8539 times the count for a non-manager, or about 15% lower, holding other factors constant.</li>
<li><code>**performance_rating:**</code> The IRR is 0.9901. For each one-level increase in performance rating, the expected number of absent days decreases by about 1%, holding other factors constant. However, this effect is not statistically significant.</li>
</ul>
<p>Just as with logistic regression, we can calculate confidence intervals for these IRRs to understand the range of plausible values for the effect.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Confidence intervals for the IRRs</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(absent_poisson_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       2.5 %    97.5 %
(Intercept)        4.0513303 5.0097586
tenure             1.0498634 1.0551020
is_manager1        0.7999133 0.9104788
performance_rating 0.9635426 1.0174134</code></pre>
</div>
</div>
<p>For example, we are 95% confident that for each additional year of tenure, the incidence rate ratio is between 1.05 and 1.055. Since this entire range is above 1, we can be confident that the relationship is positive and statistically significant.</p>
</section>
</section>
<section id="sec-overdispersion" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="sec-overdispersion"><span class="header-section-number">8.3</span> Model diagnostics: overdispersion</h2>
<p>Before we can trust our Poisson model’s conclusions, we must check its primary assumption: that the mean (expected value) and variance of the count outcome are approximately equal. That is, <span class="math inline">\(E(y) \approx Var(y)\)</span>. In real-world data, this assumption is rarely met. It is far more common for the variance to be larger than the mean<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. This is called <strong>overdispersion</strong> (<span class="math inline">\(Var(y) &gt; E(y)\)</span>).</p>
<p>Overdispersion is common for a number of reasons, including:</p>
<ol type="1">
<li><p><strong>Unobserved Heterogeneity:</strong> There may be other unmeasured factors that influence the count. For instance, in our example some employees might have chronic health conditions that make them more prone to absence. This creates extra variability in the counts that is not captured by our input variables.</p></li>
<li><p><strong>Clustering or Non-independence:</strong> Events may not be independent. If one person in a team gets a virus or flu, it might spread, leading to a cluster of absences. This violates the Poisson assumption that events are independent.</p></li>
</ol>
<p>If we use a Poisson model on overdispersed data, the coefficient estimates (<span class="math inline">\(\beta\)</span>) are still unbiased (correct on average), but their standard errors are underestimated. This makes the z-scores artificially large and the p-values artificially small. We might therefore conclude that a predictor is statistically significant when, in fact, it is not. Therefore, the model can become overconfident in its findings.</p>
<section id="detecting-overdispersion" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="detecting-overdispersion"><span class="header-section-number">8.3.1</span> Detecting overdispersion</h3>
<p>There are several ways to check for overdispersion.</p>
<ol type="1">
<li><p><strong>Compare Mean and Variance:</strong> A simple ‘rule of thumb’ check is to compare the raw mean and variance of our outcome variable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mean =</span> <span class="fu">mean</span>(absenteeism<span class="sc">$</span>days_absent), </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">variance =</span> <span class="fu">var</span>(absenteeism<span class="sc">$</span>days_absent))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     mean  variance 
 10.26243 103.25397 </code></pre>
</div>
</div>
<p>The variance (103.25) is much larger than the mean (10.26), which is a strong initial sign of overdispersion.</p></li>
<li><p><strong>Calculate the Dispersion Parameter:</strong> A more formal check comes from the model itself. The dispersion parameter is calculated by dividing the model’s residual deviance by its residual degrees of freedom. For a Poisson model, this value should be close to 1. A value significantly greater than 1 indicates overdispersion.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate dispersion parameter</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>(dispersion_param <span class="ot">&lt;-</span> <span class="fu">summary</span>(absent_poisson_model)<span class="sc">$</span>deviance<span class="sc">/</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">summary</span>(absent_poisson_model)<span class="sc">$</span>df.residual)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.735929</code></pre>
</div>
</div>
<p>Our dispersion parameter of 6.74 is substantially greater than 1, confirming that our data is overdispersed and the Poisson model is likely not appropriate.</p></li>
<li><p><strong>Formal Hypothesis Test:</strong> The <code>AER</code> package provides a formal test for overdispersion. The null hypothesis is that the data is equidispersed (mean = variance), while the alternative is that it is overdispersed. A small p-value provides evidence for overdispersion.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dispersiontest</span>(absent_poisson_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Overdispersion test

data:  absent_poisson_model
z = 13.31, p-value &lt; 2.2e-16
alternative hypothesis: true dispersion is greater than 1
sample estimates:
dispersion 
  6.926057 </code></pre>
</div>
</div>
<p>The very small p-value leads us to reject the null hypothesis and conclude that overdispersion is present. This suggests that we should search for an alternative approach that can handle overdispersed count data.</p></li>
</ol>
<p>When we have confirmed that our count data is overdispersed, there are two alternative methods we can use: Quasi-Poisson regression and negative binomial regression.</p>
</section>
<section id="quasi-poisson-regression" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="quasi-poisson-regression"><span class="header-section-number">8.3.2</span> Quasi-Poisson regression</h3>
<p>Quasi-Poisson regression, which is a simple extension of the Poisson model, relaxes the assumption that the mean and variance are equal, allowing the variance to be a linear function of the mean. That is</p>
<p><span class="math display">\[
Var(y_i) = \theta \mu_i
\]</span></p>
<p>where <span class="math inline">\(\theta\)</span> is a dispersion parameter estimated from the data and <span class="math inline">\(\mu_i\)</span> is the average event count (equivalent to <span class="math inline">\(\lambda_i\)</span> in the Poisson model). We expect <span class="math inline">\(\theta &gt; 1\)</span> in the presence of overdispersion, and a greater <span class="math inline">\(\theta\)</span> means greater dispersion. The coefficient estimates in a Quasi-Poisson model are identical to the Poisson model, but the standard errors are adjusted, which affects which input variables are returned as significant.</p>
<p>Quasi-Poisson regression can be performed in R using the <code>glm()</code> function with <code>family = "quasipoisson"</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run a quasi-poisson model</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>absent_quasi_poisson_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> days_absent <span class="sc">~</span> tenure <span class="sc">+</span> is_manager <span class="sc">+</span> performance_rating,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> absenteeism, </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"quasipoisson"</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co"># view the summary</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(absent_quasi_poisson_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = days_absent ~ tenure + is_manager + performance_rating, 
    family = "quasipoisson", data = absenteeism)

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         1.505418   0.142929  10.533   &lt;2e-16 ***
tenure              0.051144   0.003350  15.266   &lt;2e-16 ***
is_manager1        -0.157984   0.087137  -1.813   0.0702 .  
performance_rating -0.009937   0.036618  -0.271   0.7862    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for quasipoisson family taken to be 6.96191)

    Null deviance: 7544.2  on 864  degrees of freedom
Residual deviance: 5799.6  on 861  degrees of freedom
AIC: NA

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>This model suggests that the <code>is_manager</code> variable is no longer statistically significant once we account for overdispersion. The coefficient estimates are the same as in the Poisson model, so the IRRs are unchanged.</p>
</section>
<section id="negative-binomial-regression" class="level3" data-number="8.3.3">
<h3 data-number="8.3.3" class="anchored" data-anchor-id="negative-binomial-regression"><span class="header-section-number">8.3.3</span> Negative binomial regression</h3>
<p>Another option in the presence of overdispersion is to use negative binomial regression. The negative binomial distribution is a generalization of the Poisson distribution that includes an additional dispersion parameter which allows the variance to be greater than the mean.</p>
<p>The variance for a negative binomial distribution is modeled as:</p>
<p><span class="math display">\[
Var(y_i) = \mu_i + \frac{\mu_i^2}{\theta}
\]</span></p>
<p>where <span class="math inline">\(\theta\)</span> is a dispersion parameter, so the term <span class="math inline">\(\frac{\mu_i^2}{\theta}\)</span> allows for the extra variance. Note that in this model the variance is a quadratic function of the mean, rather than the linear function used in the Quasi-Poisson model. Note also that a greater <span class="math inline">\(\theta\)</span> means less dispersion, and as <span class="math inline">\(\theta\)</span> gets larger and approaches infinity, the term <span class="math inline">\(\frac{\mu_i^2}{\theta}\)</span> approaches zero, and the variance approaches the mean <span class="math inline">\(\mu_i\)</span>. In this case, the negative binomial distribution converges to the Poisson distribution.</p>
<p>We can fit a negative binomial model in R using the <code>glm.nb()</code> function from the <code>MASS</code> package. The syntax is identical to <code>glm()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># run a negative binomial model</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>absent_nb_model <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> days_absent <span class="sc">~</span> tenure <span class="sc">+</span> is_manager <span class="sc">+</span> performance_rating,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> absenteeism</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="co"># view the summary</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(absent_nb_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = days_absent ~ tenure + is_manager + performance_rating, 
    data = absenteeism, init.theta = 1.553571254, link = log)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         1.571059   0.147302  10.666   &lt;2e-16 ***
tenure              0.049723   0.003338  14.894   &lt;2e-16 ***
is_manager1        -0.138416   0.088722  -1.560    0.119    
performance_rating -0.022527   0.039176  -0.575    0.565    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(1.5536) family taken to be 1)

    Null deviance: 1208.49  on 864  degrees of freedom
Residual deviance:  978.86  on 861  degrees of freedom
AIC: 5637.1

Number of Fisher Scoring iterations: 1

              Theta:  1.5536 
          Std. Err.:  0.0894 

 2 x log-likelihood:  -5627.0750 </code></pre>
</div>
</div>
<p>The output looks very similar to the Poisson and Quasi-Poisson summaries, but with one key addition: at the bottom, we see “Theta: 1.5536”. This is the estimated dispersion parameter <span class="math inline">\(\theta\)</span>. The <code>summary()</code> also provides a standard error for <span class="math inline">\(\theta\)</span> and tests whether it is significantly different from infinity (i.e., whether the negative binomial model is a significant improvement over the Poisson model).</p>
<p>The interpretation of the coefficients is exactly the same as in the Poisson model. They are on the log-count scale, and we exponentiate them to get Incidence Rate Ratios (IRRs).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># IRRs for the negative binomial model</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>(irr_nb <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(absent_nb_model)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       (Intercept)             tenure        is_manager1 performance_rating 
         4.8117411          1.0509798          0.8707365          0.9777244 </code></pre>
</div>
</div>
<p>Let’s compare these with the IRRs from our original Poisson model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare IRRs side-by-side</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">IRR_Poisson =</span> irr, <span class="at">IRR_NB =</span> irr_nb)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   IRR_Poisson    IRR_NB
(Intercept)          4.5060347 4.8117411
tenure               1.0524742 1.0509798
is_manager1          0.8538633 0.8707365
performance_rating   0.9901123 0.9777244</code></pre>
</div>
</div>
<p>The point estimates for the IRRs are quite similar. This is expected, as the coefficients are generally unbiased even when a Poisson model is used on overdispersed data. The real difference is in the standard errors and p-values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare standard errors</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>poisson_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(absent_poisson_model)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>nb_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(absent_nb_model)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">SE_Poisson =</span> poisson_summary<span class="sc">$</span>coefficients[, <span class="st">"Std. Error"</span>],</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">SE_NB =</span> nb_summary<span class="sc">$</span>coefficients[, <span class="st">"Std. Error"</span>]</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    SE_Poisson       SE_NB
(Intercept)        0.054169623 0.147301916
tenure             0.001269716 0.003338447
is_manager1        0.033024551 0.088721754
performance_rating 0.013878275 0.039175545</code></pre>
</div>
</div>
<p>Notice that the standard errors for the negative binomial model are larger across the board. By accounting for the overdispersion, the negative binomial model provides more realistic (and conservative) estimates of the uncertainty around our coefficients. This leads to larger p-values and more trustworthy inferences. In this case, while <code>tenure</code> remains a significant input variable, we see that <code>is_manager</code> is no longer significant.</p>
</section>
<section id="comparing-poisson-and-negative-binomial-models" class="level3" data-number="8.3.4">
<h3 data-number="8.3.4" class="anchored" data-anchor-id="comparing-poisson-and-negative-binomial-models"><span class="header-section-number">8.3.4</span> Comparing Poisson and negative binomial models</h3>
<p>We have strong evidence that the negative binomial model is a better choice compared to the original Poisson model, but we can also formally compare the models. Since the Poisson model is a nested version of the negative binomial model (it’s what you get when <span class="math inline">\(\theta \to \infty\)</span>), we can use a likelihood ratio test using the <code>lmtest</code> package to see if the addition of the <span class="math inline">\(\theta\)</span> parameter provides a significant improvement in fit. This is a notable advantage of the negative binomial model over the Quasi-Poisson model, which does not have a likelihood function and therefore cannot be compared in this way.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(absent_poisson_model, absent_nb_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio test

Model 1: days_absent ~ tenure + is_manager + performance_rating
Model 2: days_absent ~ tenure + is_manager + performance_rating
  #Df  LogLik Df Chisq Pr(&gt;Chisq)    
1   4 -4459.5                        
2   5 -2813.5  1  3292  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The extremely small p-value indicates that the negative binomial model provides a significantly better fit to the data than the Poisson model.</p>
<p>We can also compare the models using the Akaike Information Criterion (AIC), which as we have learned previously is a measure of model parsimony. Since both of our models use the same input variables, a lower AIC indicates a better fit.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(absent_poisson_model, absent_nb_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     df      AIC
absent_poisson_model  4 8927.050
absent_nb_model       5 5637.075</code></pre>
</div>
</div>
<p>The AIC for the negative binomial model is substantially lower than for the Poisson model, again confirming that it is the superior and more parsimonious model for our overdispersed data.</p>
<p>Note that it is not advisable to use Pseudo R-squared metrics to compare Poisson and negative binomial models, as these metrics can be misleading in the presence of overdispersion. These metrics are more appropriate for comparing models of the same family (e.g., two Poisson models with different input variables).</p>
</section>
</section>
<section id="other-considerations-in-count-regression" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="other-considerations-in-count-regression"><span class="header-section-number">8.4</span> Other considerations in count regression</h2>
<p>In this section we provide a brief overview of some additional topics that are relevant when working with count data. For deeper study on this topic, <span class="citation" data-cites="hilbe">Hilbe (<a href="bibliography.html#ref-hilbe" role="doc-biblioref">2014</a>)</span> is an excellent introductory text, while <span class="citation" data-cites="friendly">Friendly and Meyer (<a href="bibliography.html#ref-friendly" role="doc-biblioref">2016</a>)</span> provides a more advanced treatment on the analysis of discrete data more broadly.</p>
<section id="prediction" class="level3" data-number="8.4.1">
<h3 data-number="8.4.1" class="anchored" data-anchor-id="prediction"><span class="header-section-number">8.4.1</span> Prediction</h3>
<p>Predicting expected counts from a new set of data works just like in other <code>glm</code> models. We use the <code>predict()</code> function with <code>type = "response"</code> to get the prediction on the original count scale (i.e., the expected number of events, <span class="math inline">\(\lambda_i\)</span>, over many random trials of the same input values).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define new observations</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>(new_employees <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">tenure =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">25</span>, <span class="dv">15</span>), </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">is_manager =</span> <span class="fu">as.factor</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)),</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">performance_rating =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">3</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  tenure is_manager performance_rating
1      2          0                  4
2     25          1                  3
3     15          0                  3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># predict expected days absent using our final NB model</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(absent_nb_model, new_employees, <span class="at">type =</span> <span class="st">"response"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3 
 4.856874 13.573681  9.481285 </code></pre>
</div>
</div>
</section>
<section id="exposure-and-offsets" class="level3" data-number="8.4.2">
<h3 data-number="8.4.2" class="anchored" data-anchor-id="exposure-and-offsets"><span class="header-section-number">8.4.2</span> Exposure and offsets</h3>
<p>Sometimes we are not just modeling a raw count, but a rate relative to some measure of “exposure”. For example, we might want to model the number of safety incidents, but we know that a large factory with 1,000 employees is naturally going to have more incidents than a small one with 100 employees, even if the small factory is less safe. We need to control for this exposure.</p>
<p>In this case, our outcome of interest is really the <em>rate</em> of incidents per employee. Let’s say we model</p>
<p><span class="math display">\[
E[\mathrm{incidents}_i] = \mathrm{rate}_i \times \mathrm{employees}_i
\]</span></p>
<p>Taking logs, we get</p>
<p><span class="math display">\[
\ln(E[\mathrm{incidents}_i]) = \ln(\mathrm{rate}_i) + \ln(\mathrm{employees}_i)
\]</span></p>
<p>We model the log-rate as a linear combination of input variables:</p>
<p><span class="math display">\[
\ln(\mathrm{rate}_i) = \beta_0 + \beta_1x_{1i} + \cdots
\]</span></p>
<p>Substituting this in gives:</p>
<p><span class="math display">\[
\ln(E[\mathrm{incidents}_i]) = (\beta_0 + \beta_1x_{1i} + \cdots) + \ln(\mathrm{employees}_i)
\]</span></p>
<p>The term <span class="math inline">\(\ln(\mathrm{employees}_i)\)</span> is called an <strong>offset</strong>. It is an input variable whose coefficient is fixed to 1. We include it in the model to account for the varying exposure time or group size. In R’s <code>glm()</code> and <code>glm.nb()</code>, this is specified using the <code>offset()</code> function inside the formula. For example</p>
<pre><code>glm(incidents ~ X1 + X2 + offset(log(employees)), family=poisson)</code></pre>
</section>
<section id="zero-inflation" class="level3" data-number="8.4.3">
<h3 data-number="8.4.3" class="anchored" data-anchor-id="zero-inflation"><span class="header-section-number">8.4.3</span> Zero-inflation</h3>
<p>Sometimes count data has an excess of zeros beyond what would be expected from a Poisson or negative binomial distribution. This can occur when there are two processes at work: one determining whether the event can occur at all, and another determining how many times it occurs. For example, some employees might never be absent due to perfect health and proximity to work (structural zeros), while others have some probability of absence following a count distribution.</p>
<p>If you believe there may be structural reasons for an excess of zeros in your data, you can use the <code>performance</code> package in R to check for zero-inflation in a Poisson or negative binomial model. First we will check for our Poisson model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check for zero-inflation in Poisson model</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">check_zeroinflation</span>(absent_poisson_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Check for zero-inflation

   Observed zeros: 56
  Predicted zeros: 2
            Ratio: 0.04</code></pre>
</div>
</div>
<p>The output indicates that our Poisson model may have too many zeros compared to what would normally be expected in a Poisson distribution. In this situation, we could consider using a zero-inflated model, which combines a binary model for the zero/non-zero outcome with a count model for the non-zero outcomes. The <code>pscl</code> package in R offers a function <code>zeroinfl()</code> to fit these models. The formula syntax is similar to <code>glm()</code>, but we can specify separate input variables for the zero-inflation part of the model.</p>
<p>Here we fit a zero-inflated Poisson model to our absenteeism data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pscl)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># fit zero-inflated Poisson model using all variables </span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># for both the zero-inflated and poisson parts</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>zip_model <span class="ot">&lt;-</span> <span class="fu">zeroinfl</span>(</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># poisson input variables first, binomial second</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># separated by |</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  days_absent <span class="sc">~</span> tenure <span class="sc">+</span> is_manager <span class="sc">+</span> performance_rating <span class="sc">|</span> </span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>    tenure <span class="sc">+</span> is_manager <span class="sc">+</span> performance_rating,</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> absenteeism,</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">dist =</span> <span class="st">"poisson"</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(zip_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
zeroinfl(formula = days_absent ~ tenure + is_manager + performance_rating | 
    tenure + is_manager + performance_rating, data = absenteeism, dist = "poisson")

Pearson residuals:
    Min      1Q  Median      3Q     Max 
-3.6724 -1.5248 -0.4967  0.9931  9.6365 

Count model coefficients (poisson with log link):
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         1.625565   0.054553  29.798  &lt; 2e-16 ***
tenure              0.048091   0.001281  37.542  &lt; 2e-16 ***
is_manager1        -0.140534   0.033089  -4.247 2.16e-05 ***
performance_rating -0.012928   0.013904  -0.930    0.352    

Zero-inflation model coefficients (binomial with logit link):
                   Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)        -1.39762    0.68731  -2.033 0.042007 *  
tenure             -0.05497    0.01667  -3.298 0.000974 ***
is_manager1         0.19858    0.40512   0.490 0.624014    
performance_rating -0.17071    0.18989  -0.899 0.368647    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Number of iterations in BFGS optimization: 14 
Log-likelihood: -4179 on 8 Df</code></pre>
</div>
</div>
<p>The first set of coefficients are the regression coefficients for a Poisson model fitted to the non-zero outcome values, confirming as per our previous Poisson model that higher tenure is significantly positively associated with increased absence, and that being a manager is significantly negatively associated. The second set of coefficients are from a binomial logistic regression model on an outcome of whether an observation is a structural zero. Here we see that higher tenure is significantly negatively associated with being a structural zero, meaning that employees with longer tenure are less likely to be in the always-zero group.</p>
<p>However, we know that overdispersion is present in our data, which could be a better explanation for the excess zeros, especially if we have no basis to support a structural reason. So let’s check whether there is zero-inflation in our negative binomial model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check for zero-inflation in negative binomial model</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">check_zeroinflation</span>(absent_nb_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Check for zero-inflation

   Observed zeros: 56
  Predicted zeros: 49
            Ratio: 0.88</code></pre>
</div>
</div>
<p>It seems unlikely based on this check that zero-inflation is an issue in the negative binomial model, so the excess zeros could well be a consequence of overdispersion. Nevertheless, for completeness, we can fit a zero-inflated negative binomial model as well.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit zero-inflated negative binomial model</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>zinb_model <span class="ot">&lt;-</span> <span class="fu">zeroinfl</span>(</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># negative binomial input variables first, binomial second</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># separated by |</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  days_absent <span class="sc">~</span> tenure <span class="sc">+</span> is_manager <span class="sc">+</span> performance_rating <span class="sc">|</span> </span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>    tenure <span class="sc">+</span> is_manager <span class="sc">+</span> performance_rating,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> absenteeism,</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">dist =</span> <span class="st">"negbin"</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(zinb_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
zeroinfl(formula = days_absent ~ tenure + is_manager + performance_rating | 
    tenure + is_manager + performance_rating, data = absenteeism, dist = "negbin")

Pearson residuals:
    Min      1Q  Median      3Q     Max 
-1.2341 -0.7063 -0.2438  0.4825  4.6896 

Count model coefficients (negbin with log link):
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         1.638010   0.155648  10.524  &lt; 2e-16 ***
tenure              0.049110   0.003451  14.231  &lt; 2e-16 ***
is_manager1        -0.123632   0.090017  -1.373    0.170    
performance_rating -0.035067   0.040599  -0.864    0.388    
Log(theta)          0.511736   0.080944   6.322 2.58e-10 ***

Zero-inflation model coefficients (binomial with logit link):
                   Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)        -0.94964    3.24416  -0.293    0.770
tenure             -0.04573    0.09641  -0.474    0.635
is_manager1         0.76056    1.25077   0.608    0.543
performance_rating -0.82878    0.90994  -0.911    0.362
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Theta = 1.6682 
Number of iterations in BFGS optimization: 20 
Log-likelihood: -2812 on 9 Df</code></pre>
</div>
</div>
<p>The more conservative negative binomial model suggests that there are no variables significantly associated with being a member of the structural zero group, and confirms the findings from our previous negative binomial model that only tenure is significantly positively associated with increased absence. This suggests that zero-inflation is not a concern in this case.</p>
</section>
</section>
<section id="poisson-and-negative-binomial-regression-using-python" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="poisson-and-negative-binomial-regression-using-python"><span class="header-section-number">8.5</span> Poisson and negative binomial regression using Python</h2>
<p>In Python, count models can be fitted using the <code>statsmodels</code> library, very similar to the linear and logistic regression models we have already seen. First let’s download our data set.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>url<span class="op">=</span><span class="st">"https://peopleanalytics-regression-book.org/data/absenteeism.csv"</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>absenteeism <span class="op">=</span> pd.read_csv(url)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now, we can fit our Poisson model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Poisson Model</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>poisson_model <span class="op">=</span> smf.glm(</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>    formula<span class="op">=</span><span class="st">"days_absent ~ tenure + is_manager + performance_rating"</span>,</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>absenteeism,</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>    family<span class="op">=</span>sm.families.Poisson()</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>).fit()</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(poisson_model.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:            days_absent   No. Observations:                  865
Model:                            GLM   Df Residuals:                      861
Model Family:                 Poisson   Df Model:                            3
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -4459.5
Date:                Tue, 24 Feb 2026   Deviance:                       5799.6
Time:                        14:17:42   Pearson chi2:                 5.99e+03
No. Iterations:                     5   Pseudo R-squ. (CS):             0.8669
Covariance Type:            nonrobust                                         
======================================================================================
                         coef    std err          z      P&gt;|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              1.5054      0.054     27.791      0.000       1.399       1.612
tenure                 0.0511      0.001     40.280      0.000       0.049       0.054
is_manager            -0.1580      0.033     -4.784      0.000      -0.223      -0.093
performance_rating    -0.0099      0.014     -0.716      0.474      -0.037       0.017
======================================================================================</code></pre>
</div>
</div>
<p>We exponentiate the coefficients to get Incidence Rate Ratios (IRRs):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.exp(poisson_model.params))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Intercept             4.506035
tenure                1.052474
is_manager            0.853863
performance_rating    0.990112
dtype: float64</code></pre>
</div>
</div>
<p>We can also fit our negative binomial model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit negative binomial Model</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>nb_model <span class="op">=</span> smf.glm(</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>    formula<span class="op">=</span><span class="st">"days_absent ~ tenure + is_manager + performance_rating"</span>,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>absenteeism,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>    family<span class="op">=</span>sm.families.NegativeBinomial()</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>).fit()</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(nb_model.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:            days_absent   No. Observations:                  865
Model:                            GLM   Df Residuals:                      861
Model Family:        NegativeBinomial   Df Model:                            3
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -2842.3
Date:                Tue, 24 Feb 2026   Deviance:                       702.79
Time:                        14:17:43   Pearson chi2:                     548.
No. Iterations:                     6   Pseudo R-squ. (CS):             0.1645
Covariance Type:            nonrobust                                         
======================================================================================
                         coef    std err          z      P&gt;|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              1.5732      0.178      8.814      0.000       1.223       1.923
tenure                 0.0496      0.004     12.290      0.000       0.042       0.058
is_manager            -0.1373      0.107     -1.278      0.201      -0.348       0.073
performance_rating    -0.0228      0.048     -0.479      0.632      -0.116       0.070
======================================================================================</code></pre>
</div>
</div>
<p>If needed, zero-inflated models can be fit using the <code>statsmodels</code> library’s <code>ZeroInflatedPoisson</code> and <code>ZeroInflatedNegativeBinomialP</code> classes.</p>
<p></p>
</section>
<section id="learning-exercises" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="learning-exercises"><span class="header-section-number">8.6</span> Learning exercises</h2>
<section id="discussion-questions" class="level3" data-number="8.6.1">
<h3 data-number="8.6.1" class="anchored" data-anchor-id="discussion-questions"><span class="header-section-number">8.6.1</span> Discussion questions</h3>
<ol type="1">
<li>What are the key characteristics of count data? Why is linear regression not a suitable method for modeling it?</li>
<li>What are the main assumptions of the Poisson distribution? Which one is most frequently violated in practice?</li>
<li>In Poisson regression, we model the log of the expected count as a linear function of the input variables. Why do we use the log transformation? What does this imply about the effect of input variables on the expected count itself?</li>
<li>Explain the concept of an Incidence Rate Ratio (IRR). If a predictor has an IRR of 1.15, how would you interpret its effect? What about an IRR of 0.85?</li>
<li>What is overdispersion? Describe two common reasons why it might occur in people-related data.</li>
<li>What are the consequences of ignoring overdispersion and using a Poisson model regardless?</li>
<li>Describe three methods you could use to test for overdispersion in your data.</li>
<li>How does the negative binomial distribution differ from the Poisson distribution? Explain the role of the dispersion parameter <span class="math inline">\(\theta\)</span>.</li>
<li>When would you use an offset in a count model? Provide a people-related example.</li>
<li>What are zero-inflated models and when might they be needed?</li>
</ol>
</section>
<section id="data-exercises" class="level3" data-number="8.6.2">
<h3 data-number="8.6.2" class="anchored" data-anchor-id="data-exercises"><span class="header-section-number">8.6.2</span> Data exercises</h3>
<p>A retail company wants to understand factors affecting the number of customer complaints received about their telephone customer service representatives. Load the <code>complaints</code> data set via the <code>peopleanalyticsdata</code> package or download it from the internet<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. It contains the following data for 376 representatives:</p>
<ul>
<li><code>n_complaints</code>: Number of complaints received about the representative in the past year</li>
<li><code>experience</code>: Years of experience in customer service</li>
<li><code>training_hours</code>: Hours of training received in the past year<br>
</li>
<li><code>workload</code>: Average number of customer interactions per day</li>
<li><code>shift</code>: The primary shift worked (Day, Evening, or Night)</li>
<li><code>remote</code>: Whether the representative works remotely (1 = yes, 0 = no)</li>
<li><code>satisfaction_score</code>: The representative’s job satisfaction score (1-10 scale of increasing satisfaction)</li>
</ul>
<ol type="1">
<li>Load the data and obtain statistical summaries. Check data types and create an appropriate visualization to understand the distribution of <code>n_complaints</code>. How would you describe the distribution of <code>n_complaints</code>?</li>
<li>Check whether the mean and variance of <code>n_complaints</code> are similar. What does this tell you about potential overdispersion?</li>
<li>Fit a Poisson regression model using all input variables. Which variables have significant effects on the number of complaints?</li>
<li>Calculate and interpret the incidence rate ratios for the significant input variables.</li>
<li>Perform diagnostic checks for overdispersion in your Poisson model.</li>
<li>Fit a Quasi-Poisson regression model. How do the standard errors and significance of input variables change compared to the Poisson model?</li>
<li>Fit a negative binomial regression model with the same input variables. How do the results compare to the Poisson model?</li>
<li>Compare the Poisson and negative binomial models using AIC and likelihood ratio tests. Which model is preferred and why?</li>
<li>Determine the expected number of complaints for three hypothetical customer service representatives with different characteristics. Compare the predictions from both models.</li>
<li>Write a brief report explaining your findings and recommendations for reducing customer complaints.</li>
</ol>
<p> </p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-friendly" class="csl-entry" role="listitem">
Friendly, Michael, and David Meyer. 2016. <em>Discrete Data Analysis with <span>R</span>: Visualization and Modeling Techniques for Categorical and Count Data</em>.
</div>
<div id="ref-hilbe" class="csl-entry" role="listitem">
Hilbe, Joseph M. 2014. <em>Modeling Count Data</em>.
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>In fact, the distribution had already been discovered by the famous French mathematician Abraham De Moivre in the early 18th century.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>In more rare circumstances, the variance may be smaller than the mean, which is called <strong>underdispersion</strong> (<span class="math inline">\(Var(y) &lt; E(y)\)</span>). Similar methods to those described in this chapter can also be used to treat underdispersed data.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>https://peopleanalytics-regression-book.org/data/complaints.csv<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/peopleanalytics-regression-book\.org\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ordinal_regression.html" class="pagination-link" aria-label="Proportional Odds Logistic Regression for Ordered Category Outcomes">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Proportional Odds Logistic Regression for Ordered Category Outcomes</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./hierarchical_data.html" class="pagination-link" aria-label="Modeling Explicit and Latent Hierarchy in Data">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modeling Explicit and Latent Hierarchy in Data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/keithmcnulty/regression-handbook-2nd-edition/edit/main/poisson_nb.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/keithmcnulty/regression-handbook-2nd-edition/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>